#!/usr/bin/env bash
# Shared release configuration. Sourced by eyes/shell/build.sh (to stamp the
# feed into Info.plist) and by the scripts in this directory.
#
# Override anything here by exporting it first. The one value that is a secret
# is the *private* EdDSA key, which never appears in this repo — Sparkle keeps
# it in the login keychain under SPARKLE_KEY_ACCOUNT. The public key below is
# meant to be published; it is what lets every installed copy of Neon verify
# that an update really came from Nick.
#
# First-time setup is in docs/release.md.

# Generated by tools/release-setup.sh on 2026-08-03. The private half is in
# the login keychain under SPARKLE_KEY_ACCOUNT and must never leave it; this
# half is meant to be published, and build.sh writes it into the generated
# Info.plist as SUPublicEDKey. (Sparkle's own setup message tells you to edit
# a plist by hand — that is advice for Xcode projects. Neon's Info.plist is
# regenerated on every build, so this file is the only place to put it.)
#
# Blank in a fresh clone, and build.sh then leaves the Sparkle keys out
# entirely, so the settings panel reports that the build doesn't do updates —
# which is the truth, and better than a button that can only fail.
SPARKLE_PUBLIC_KEY="${SPARKLE_PUBLIC_KEY:-adS7poqRH0qC8XiqOHfhSgCBvab/lcQVpgM5xk5IDbI=}"

SPARKLE_VERSION="${SPARKLE_VERSION:-2.9.1}"
SPARKLE_KEY_ACCOUNT="${SPARKLE_KEY_ACCOUNT:-com.nickfarina.neon}"

# GitHub Pages, served from main/docs. docs/.nojekyll keeps Pages from trying
# to build the implementation notes in that folder into a website — the only
# file there anybody is meant to fetch is appcast.xml.
SPARKLE_SITE_URL="${SPARKLE_SITE_URL:-https://nfarina.github.io/neon}"
SPARKLE_FEED_URL="${SPARKLE_FEED_URL:-${SPARKLE_SITE_URL%/}/appcast.xml}"

SPARKLE_RELEASES_URL="${SPARKLE_RELEASES_URL:-https://github.com/nfarina/neon/releases}"
SPARKLE_RELEASE_DOWNLOAD_BASE_URL="${SPARKLE_RELEASE_DOWNLOAD_BASE_URL:-https://github.com/nfarina/neon/releases/download}"

SPARKLE_TOOLS_REPO="${SPARKLE_TOOLS_REPO:-sparkle-project/Sparkle}"
SPARKLE_TOOLS_ARCHIVE="${SPARKLE_TOOLS_ARCHIVE:-Sparkle-${SPARKLE_VERSION}.tar.xz}"
SPARKLE_TOOLS_CACHE_DIR="${SPARKLE_TOOLS_CACHE_DIR:-build/sparkle-tools/${SPARKLE_VERSION}}"

# Notarization. `xcrun notarytool store-credentials neon-notary` once, then
# this profile name is all the scripts need.
NOTARY_PROFILE="${NOTARY_PROFILE:-neon-notary}"
